# Generated by Django 4.0.2 on 2022-03-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authentication',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
