# Generated by Django 4.0.2 on 2022-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_post',
            name='tag',
            field=models.ManyToManyField(to='portal.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='portal.Tag'),
        ),
    ]
