# Generated by Django 4.0.2 on 2022-04-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_request',
            name='academics_performance',
        ),
    ]
