# Generated by Django 4.0 on 2022-04-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='date',
        ),
    ]
