# Generated by Django 4.0.2 on 2022-06-03 09:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Featured_Sponser',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='achievements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department'),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='image',
            field=models.ImageField(upload_to='student_images'),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='other_performance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('O', 'Opportunity'), ('S', 'Seeking Job'), ('I', 'Internship')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tech_help_post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='tech_help_post',
            name='stack',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tech_help_post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
