# Generated by Django 4.0 on 2022-04-07 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Post',
        ),
    ]
