# Generated by Django 4.0 on 2022-02-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_mentor_post_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_support',
            old_name='desc',
            new_name='description',
        ),
    ]
