# Generated by Django 4.0.2 on 2022-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_featured_sponser_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='../static/image/character.png', null=True, upload_to='profile_picture'),
        ),
    ]
