# Generated by Django 4.0 on 2022-04-07 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_finance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finance',
            name='student_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portal.finance_request'),
            preserve_default=False,
        ),
    ]
