# Generated by Django 4.0.2 on 2022-05-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_responsemessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_help_post',
            name='deadline',
        ),
    ]
