# Generated by Django 4.0 on 2022-04-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_finance_date_finance_student_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posteducationdetail',
            old_name='currently_pursing_this',
            new_name='currently_pursing',
        ),
    ]
