# Generated by Django 4.0.2 on 2022-05-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_featured_sponser_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_sponser',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
