# Generated by Django 4.0 on 2022-02-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_authentication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience_Detail',
            new_name='ExperienceDetail',
        ),
        migrations.RenameModel(
            old_name='Mentor_Post',
            new_name='MentorPost',
        ),
        migrations.RenameModel(
            old_name='Mentor_Post_Response',
            new_name='MentorPostResponse',
        ),
        migrations.RenameModel(
            old_name='Response_Message',
            new_name='MentorResponseMessage',
        ),
        migrations.RenameModel(
            old_name='Post_Education_Detail',
            new_name='PostEducationDetail',
        ),
        migrations.RenameModel(
            old_name='Post_Response',
            new_name='PostResponse',
        ),
        migrations.RenameModel(
            old_name='Mentor_Response_Message',
            new_name='ResponseMessage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deadLine',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AlterField(
            model_name='responsemessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.post'),
        ),
        migrations.CreateModel(
            name='Corpus_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('total_amount', models.IntegerField()),
                ('modeofpayment', models.CharField(choices=[('O', 'Online Banking'), ('N', 'Net Banking'), ('U', 'UPI'), ('C', 'Credit/Debit card'), ('A', 'Cash')], max_length=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.user')),
            ],
        ),
    ]
