# Generated by Django 4.0.2 on 2022-03-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_post_content_alter_tech_help_post_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='posted_by',
        ),
        migrations.RenameField(
            model_name='tech_help_post',
            old_name='user',
            new_name='posted_by',
        ),
    ]
