# Generated by Django 4.0.2 on 2022-05-10 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_featured_sponser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_sponser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to=settings.AUTH_USER_MODEL),
        ),
    ]
