# Generated by Django 4.0 on 2022-02-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_experience_detail_experiencedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorresponsemessage',
            name='postResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.mentorpostresponse'),
        ),
        migrations.AlterField(
            model_name='mentorresponsemessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.mentorpost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsemessage',
            name='postResponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.postresponse'),
        ),
    ]
