# Generated by Django 4.0 on 2022-04-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_currently_pursing_this_posteducationdetail_currently_pursing'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_request',
            name='percentage_or_HSC_marks',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
