# Generated by Django 4.0.2 on 2022-03-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_post_user_tech_help_post_user_alter_post_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_request',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
