# Generated by Django 4.0 on 2022-02-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_corporsefund_remove_student_support_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience_Detail',
            new_name='ExperienceDetail',
        ),
        migrations.RenameModel(
            old_name='Mentor_Post',
            new_name='MentorPost',
        ),
        migrations.RenameModel(
            old_name='Mentor_Post_Response',
            new_name='MentorPostResponse',
        ),
        migrations.RenameModel(
            old_name='Mentor_Response_Message',
            new_name='MentorResponseMessage',
        ),
        migrations.RenameModel(
            old_name='Post_Response',
            new_name='PostResponse',
        ),
        migrations.RenameModel(
            old_name='Response_Message',
            new_name='ResponseMessage',
        ),
    ]
