# Generated by Django 4.0 on 2022-04-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_user_batch_alter_user_current_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_request',
            name='percentage_or_HSC_marks',
        ),
    ]
