# Generated by Django 4.0 on 2022-02-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_mentorpost_content_and_more'),
        ('portal', '0007_rename_experience_detail_experiencedetail_and_more'),
    ]

    operations = [
    ]
