# Generated by Django 4.0.2 on 2022-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_finance_request_highschoolmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_request',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='finance_request',
            name='highschoolmark',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
