# Generated by Django 4.0 on 2022-02-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_post_education_detail_posteducationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(choices=[('G', 'Good'), ('A', 'Average'), ('B', 'Bad')], max_length=1)),
                ('about', models.TextField()),
                ('reason', models.TextField()),
                ('amount', models.IntegerField()),
                ('highschoolmark', models.IntegerField()),
                ('anyarrears', models.BooleanField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currentsem', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], max_length=1)),
                ('achievements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('modeofpayment', models.CharField(choices=[('O', 'Online Banking'), ('N', 'Net Banking'), ('U', 'UPI'), ('C', 'Credit/Debit card'), ('A', 'Cash')], max_length=1)),
                ('studentdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.studdetails')),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.user')),
            ],
        ),
    ]
