# Generated by Django 4.0.2 on 2022-03-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_finance_request_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_request',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='Finance_request',
        ),
    ]
