# Generated by Django 4.0.2 on 2022-03-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_finance_request_finance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_request',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='Finance_request',
        ),
    ]
