# Generated by Django 4.0.2 on 2022-03-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_acheivements_marks_finance_request_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_request',
            name='deadline',
            field=models.DateField(),
        ),
    ]
