# Generated by Django 4.0.2 on 2022-03-11 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_alter_finance_request_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_request',
            name='deadline',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
