# Generated by Django 4.0.2 on 2022-03-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_alter_finance_request_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_request_Post_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdeskpost', to='portal.finance_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdeskuser', to='portal.finance_request')),
            ],
        ),
        migrations.CreateModel(
            name='Finance_request_Response_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timeStamp', models.DateTimeField()),
                ('postResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_response', to='portal.finance_request_post_response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_message_user', to='portal.finance_request')),
            ],
        ),
    ]
