# Generated by Django 4.0.2 on 2022-03-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_finance_request_post_response_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acheivements',
            new_name='Acheivement',
        ),
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
    ]
