# Generated by Django 4.0.2 on 2022-03-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_rename_acheivements_acheivement_rename_marks_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheivement',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
