# Generated by Django 4.0.2 on 2022-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_alter_acheivement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_request',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
