# Generated by Django 4.0.2 on 2022-03-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_alter_finance_request_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_request',
            name='image',
            field=models.ImageField(upload_to='student_images/'),
        ),
    ]
