# Generated by Django 4.0.2 on 2022-03-22 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_alter_finance_request_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_With_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesage', models.TextField()),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('form_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postid', to='portal.finance_request')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
