# Generated by Django 4.0 on 2022-03-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_alter_finance_request_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_from', models.DateTimeField()),
                ('created_to', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
