# Generated by Django 4.0.2 on 2022-03-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_chat_with_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_with_staff',
            old_name='mesage',
            new_name='message',
        ),
    ]
