# Generated by Django 4.0.2 on 2022-03-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_rename_mesage_chat_with_staff_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat_With_Staff',
        ),
    ]
