# Generated by Django 4.0.2 on 2022-03-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_delete_chat_with_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance_request_response_message',
            name='postResponse',
        ),
        migrations.RemoveField(
            model_name='finance_request_response_message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Finance_request_Post_Response',
        ),
        migrations.DeleteModel(
            name='Finance_request_Response_Message',
        ),
    ]
