# Generated by Django 4.0.2 on 2022-03-25 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_remove_finance_request_response_message_postresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_request_Post_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdeskpost', to='portal.finance_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdeskuser', to='portal.finance_request')),
            ],
        ),
        migrations.CreateModel(
            name='Finance_request_Response_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('message_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('postResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_response', to='portal.finance_request_post_response')),
            ],
        ),
    ]
