# Generated by Django 4.0.2 on 2022-03-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_finance_request_post_response_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance_request_Response_Message',
        ),
    ]
