# Generated by Django 4.0.2 on 2022-03-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_delete_finance_request_response_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_request_Response_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timeStamp', models.DateTimeField()),
                ('postResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.finance_request_post_response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.finance_request')),
            ],
        ),
    ]
