# Generated by Django 4.0.2 on 2022-03-29 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_finance_request_response_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_help_post',
            name='category',
        ),
        migrations.AlterField(
            model_name='tech_help_post',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to=settings.AUTH_USER_MODEL),
        ),
    ]
