# Generated by Django 4.0.2 on 2022-03-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_remove_tech_help_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='studentdetails',
            new_name='student_details',
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='studentname',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='finance_request_response_message',
            old_name='timeStamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='finance_request_response_message',
            old_name='postResponse',
            new_name='post_response',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timeStamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deadLine',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postType',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='responsemessage',
            old_name='timeStamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='responsemessage',
            old_name='postResponse',
            new_name='post_response',
        ),
        migrations.RenameField(
            model_name='tech_help_post',
            old_name='timeStamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tech_help_post',
            old_name='deadLine',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='tech_help_responsemessage',
            old_name='timeStamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='tech_help_responsemessage',
            old_name='postResponse',
            new_name='post_response',
        ),
    ]
