# Generated by Django 4.1.1 on 2023-02-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="image/character.png",
                null=True,
                upload_to="profile_picture",
            ),
        ),
    ]
