# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - EMAIL_ADMIN=admin@gmail.com
      - EMAIL_HOST='sandbox.smtp.mailtrap.io'
      - EMAIL_HOST_USER='fa92b5a4321224'
      - EMAIL_HOST_PASSWORD='0db95d7c9246d3'
      - EMAIL_PORT='2525'
      - EMAIL_USE_TLS=True
      - EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
      - SECRET_KEY=django-insecure-nj@^0^n%be!u=8!o5ui7efi*b7)iad2(jgw06^flv=z4i$z%7_
      - LOGIN_REDIRECT_URL=home
      - LOGOUT_REDIRECT_URL=login
      - DJANGO_SETTINGS_MODULE=alumni_portal.settings
      - DATABASE_URL=mysql://admin_user:admin_user@localhost:3306/alumni_portal
      - DEBUG=True



# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

