# Generated by Django 4.0 on 2021-12-16 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.FileField(upload_to='images/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/partner')),
            ],
        ),
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/speaker')),
                ('designation', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster', models.FileField(upload_to='images/poster')),
                ('venue', models.CharField(max_length=200)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('participation_limit', models.IntegerField()),
                ('event_start_at', models.DateTimeField()),
                ('event_end_at', models.DateTimeField()),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('registration_start_time', models.TimeField()),
                ('registration_end_time', models.TimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('gallery', models.ManyToManyField(related_name='media', to='event.media')),
                ('partn_er', models.ManyToManyField(related_name='partner', to='event.partner')),
                ('speak_er', models.ManyToManyField(related_name='speaker', to='event.speaker')),
            ],
        ),
    ]
