# Generated by Django 4.0 on 2021-12-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.FileField(upload_to='poster'),
        ),
        migrations.AlterField(
            model_name='media',
            name='gallery',
            field=models.FileField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='partner'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(upload_to='speaker'),
        ),
    ]
