# Generated by Django 4.0 on 2021-12-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='list_of_event',
            field=models.CharField(choices=[('select_event', 'Select event'), ('symposium', 'Symposium'), ('workshop', 'Workshop'), ('hackathon', 'Hackathon')], default='select_event', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='mode_of_event',
            field=models.CharField(choices=[('select_mode', 'Select the mode of event'), ('intercollege-event', 'Inter college Event'), ('intracollege-event', 'Intra college Event')], default='select_mode', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('select_type', 'Select the type of event'), ('technical', 'Technical'), ('non-technical', 'Non Technical')], default='select_type', max_length=100),
        ),
    ]
