# Generated by Django 4.0 on 2021-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_list_of_event_event_mode_of_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='partn_er',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speak_er',
        ),
        migrations.AddField(
            model_name='event',
            name='partner',
            field=models.ManyToManyField(related_name='partner', to='event.Partner'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(related_name='speaker', to='event.Speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(related_name='media', to='event.Media'),
        ),
    ]
