# Generated by Django 4.0 on 2021-12-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event', '0006_remove_event_partn_er_remove_event_speak_er_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('regno', models.IntegerField()),
                ('degree', models.CharField(choices=[('s', 'Seelct'), ('btech', 'Bachelor of Technology'), ('be', 'Bachelor of Engineering')], default='s', max_length=100)),
                ('specialization', models.CharField(choices=[('s', 'Seelct'), ('it', 'Information Technology'), ('cse', 'Computer Science Engineering'), ('aids', 'Artificial Inteligence and Data Science'), ('eee', 'ELectrical and Electronic Engineering'), ('ece', 'Electronics and Communication Engineering'), ('mech', 'Mechanical Engineering')], default='s', max_length=100)),
                ('phoneno', models.IntegerField()),
                ('college', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user')),
            ],
        ),
    ]
