# Generated by Django 4.0 on 2021-12-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_district_student_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
