# Generated by Django 4.0 on 2021-12-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_student_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
