# Generated by Django 4.0 on 2021-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_student_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='add_other_assesment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='amplifier',
            field=models.CharField(choices=[('select', 'Select Amplifer'), ('120hz', '120 Hz Amplifier'), ('90hz', '90 Hz Amplifier')], default='select', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='budjet',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='budjet_money',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cheif_patron',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='co_coordinator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.CharField(choices=[('select', 'Select Department'), ('it', 'Information Technology'), ('cse', 'Computer Science and Engineering'), ('aids', 'Artificial Intelegence and Data Science'), ('ece', 'Electronics and Communication Engineering'), ('eee', 'ELectrical and Electronic Engineering'), ('mech', 'Mechanical Engineering')], default='select', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('select_type', 'Select the type of event'), ('technical', 'Technical'), ('non-technical', 'Non Technical')], default='select_type', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='mic',
            field=models.CharField(choices=[('s', 'Select'), ('0', 'Null'), ('1', '1 Mic'), ('2', '2 Mic'), ('3', '3 Mic'), ('4', '4 Mic')], default='s', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='organizing_secretary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='patron',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='student_coordinator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='list_of_event',
            field=models.CharField(choices=[('select_event', 'Select event'), ('symposium', 'Symposium'), ('workshop', 'Workshop'), ('hackathon', 'Hackathon')], default='select_event', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='mode_of_event',
            field=models.CharField(choices=[('select_mode', 'Select the mode of event'), ('intercollege-event', 'Inter college Event'), ('intracollege-event', 'Intra college Event')], default='select_mode', max_length=50),
        ),
        migrations.RemoveField(
            model_name='event',
            name='speaker',
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.CharField(choices=[('s', 'Select'), ('0', 'Null'), ('1', '1 Mic'), ('2', '2 Mic'), ('3', '3 Mic'), ('4', '4 Mic')], default='s', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('select', 'Select'), ('Dept', 'Department Event'), ('college', 'College')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(choices=[('s', 'Select'), ('btech', 'Bachelor of Technology'), ('be', 'Bachelor of Engineering')], default='s', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialization',
            field=models.CharField(choices=[('s', 'Seelct'), ('it', 'Information Technology'), ('cse', 'Computer Science Engineering'), ('aids', 'Artificial Inteligence and Data Science'), ('ece', 'Electronics and Communication Engineering'), ('eee', 'ELectrical and Electronic Engineering'), ('mech', 'Mechanical Engineering')], default='s', max_length=100),
        ),
    ]
