# Generated by Django 4.0 on 2021-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_add_other_assesment_event_amplifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='main',
        ),
    ]
