# Generated by Django 4.0 on 2021-12-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_event_main_event_delete_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='main_event',
        ),
    ]
