# Generated by Django 4.0 on 2021-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_remove_event_main_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(null=True),
        ),
    ]
