# Generated by Django 4.0 on 2021-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_main_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_event',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
