# Generated by Django 4.0 on 2021-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_budjet_event_main_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(choices=[('s', 'Select'), ('0', 'Null'), ('1', '1 Speaker'), ('2', '2 Speaker'), ('3', '3 Speaker'), ('4', '4 Speaker')], default='s', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('select', 'Select'), ('Dept', 'Department Event'), ('college', 'College Event')], default='select', max_length=20),
        ),
    ]
