# Generated by Django 4.0 on 2021-12-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_event_speaker_alter_event_type_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participation_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
