# Generated by Django 4.0 on 2021-12-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_event_participation_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('question', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prize_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='prize')),
                ('prize_money', models.PositiveBigIntegerField()),
                ('prize_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='theme')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='budjet_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_mode',
            field=models.CharField(choices=[('select_type', 'Select the type of event'), ('both', 'Both'), ('technical', 'Technical'), ('non-technical', 'Non Technical')], default='select_type', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='faqs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='event.faqs'),
        ),
        migrations.AddField(
            model_name='event',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='event.feedback'),
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='event.prize'),
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='event.theme'),
        ),
    ]
