# Generated by Django 4.0 on 2021-12-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_faqs_feedback_prize_theme_alter_event_budjet_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='faqs',
        ),
        migrations.AddField(
            model_name='event',
            name='faqs',
            field=models.ManyToManyField(null=True, related_name='faqs', to='event.Faqs'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='feedback',
        ),
        migrations.AddField(
            model_name='event',
            name='feedback',
            field=models.ManyToManyField(null=True, related_name='feedback', to='event.Feedback'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='prize',
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.ManyToManyField(null=True, related_name='prize', to='event.Prize'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.ManyToManyField(null=True, related_name='theme', to='event.Theme'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='prize_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(null=True, upload_to='theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
