# Generated by Django 4.0 on 2021-12-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_event_faqs_event_faqs_remove_event_feedback_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faqs',
            new_name='Faq',
        ),
    ]
