# Generated by Django 4.0 on 2021-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_rename_faqs_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='faqs',
            field=models.ManyToManyField(related_name='faqs', to='event.Faq'),
        ),
        migrations.AlterField(
            model_name='event',
            name='feedback',
            field=models.ManyToManyField(related_name='feedback', to='event.Feedback'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize',
            field=models.ManyToManyField(related_name='prize', to='event.Prize'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.ManyToManyField(related_name='theme', to='event.Theme'),
        ),
    ]
