# Generated by Django 4.0 on 2021-12-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_alter_event_faqs_alter_event_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='co_coordinator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='faqs',
            field=models.ManyToManyField(null=True, related_name='faqs', to='event.Faq'),
        ),
        migrations.AlterField(
            model_name='event',
            name='partner',
            field=models.ManyToManyField(null=True, related_name='partner', to='event.Partner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prize',
            field=models.ManyToManyField(null=True, related_name='prize', to='event.Prize'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.ManyToManyField(null=True, related_name='theme', to='event.Theme'),
        ),
    ]
