# Generated by Django 4.0 on 2021-12-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_alter_event_co_coordinator_alter_event_coordinator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='feedback',
            field=models.ManyToManyField(blank=True, null=True, related_name='feedback', to='event.Feedback'),
        ),
    ]
